// Persian (فارسی) interface text. The English text is the key; anything missing falls back to English.
enum FarsiStrings {
    static let table: [String: String] = [
        // Navigation
        "Transcribe": "تبدیل به متن",
        "Queue": "صف کارها",
        "History": "تاریخچه",
        "Speak": "خواندن متن",
        "Live": "گفتار زنده",
        "Telegram": "تلگرام",
        "Go": "برو",
        "Start Queue": "شروع صف",
        "Add Files…": "افزودن فایل…",

        // Transcribe
        "Drop audio or video files. Hush turns the speech into text, right on this Mac.": "فایل صوتی یا ویدیویی را اینجا رها کنید. هاش گفتار را روی همین مک به متن تبدیل می‌کند.",
        "Drop files here or click to choose": "فایل‌ها را اینجا رها کنید یا برای انتخاب کلیک کنید",
        "OGG, Opus, WAV, MP3, M4A, FLAC, MP4, MKV, MOV, WebM and more": "OGG، Opus، WAV، MP3، M4A، FLAC، MP4، MKV، MOV، WebM و قالب‌های دیگر",
        "Ready to start": "آماده‌ی شروع",
        "Clear": "پاک کردن",
        "Start": "شروع",
        "Start %d jobs": "شروع %d کار",
        "Spoken language": "زبان گفتار",
        "Auto-detect": "تشخیص خودکار",
        "Model": "مدل",
        "No model yet": "هنوز مدلی دانلود نشده",
        "Get more…": "مدل‌های بیشتر…",
        "Save as": "ذخیره با قالب",
        "Save to": "محل ذخیره",
        "Next to each file": "کنار هر فایل",
        "Change…": "تغییر…",
        "Reset": "بازنشانی",
        "Where should transcripts be saved?": "متن‌ها کجا ذخیره شوند؟",
        "Also send the result to %@": "نتیجه برای %@ هم فرستاده شود",
        "your chat": "گفت‌وگوی شما",
        "Advanced": "تنظیمات پیشرفته",
        "Translate": "ترجمه",
        "Translate the speech into English": "گفتار به انگلیسی ترجمه شود",
        "Persian text": "متن فارسی",
        "Fix Persian letters and spacing (ی، ک، نیم‌فاصله)": "اصلاح حروف و فاصله‌گذاری فارسی (ی، ک، نیم‌فاصله)",
        "Silence": "سکوت",
        "Skip silent parts (VAD)": "رد کردن بخش‌های بی‌صدا (VAD)",
        "Download VAD model": "دانلود مدل VAD",
        "Line length": "طول هر خط",
        "Automatic": "خودکار",
        "%d characters": "%d نویسه",
        "Split on words": "شکستن خط بین کلمه‌ها",
        "CPU threads": "رشته‌های پردازنده",
        "Vocabulary": "واژه‌ها",
        "Names and terms to expect, e.g. Hush, whisper.cpp": "نام‌ها و اصطلاحاتی که در فایل هست، مثلاً هاش، whisper.cpp",
        "Helps with the spelling of names and technical words.": "به درست نوشته شدن نام‌ها و واژه‌های تخصصی کمک می‌کند.",
        "TXT with times": "TXT با زمان",
        "About %@ left": "حدود %@ مانده",
        "Pause": "توقف موقت",
        "Resume": "ادامه",
        "Cancel": "لغو",
        "Choose audio or video files, or a folder": "فایل صوتی، ویدیو یا یک پوشه انتخاب کنید",

        // Export format titles
        "Plain text (.txt)": "متن ساده (.txt)",
        "Text with times (.txt)": "متن با زمان (.txt)",
        "Subtitles (.srt)": "زیرنویس (.srt)",
        "Web subtitles (.vtt)": "زیرنویس وب (.vtt)",
        "Lyrics (.lrc)": "متن ترانه (.lrc)",
        "Spreadsheet (.csv)": "جدول (.csv)",
        "JSON (.json)": "JSON (.json)",
        "Markdown (.md)": "مارک‌داون (.md)",
        "Word (.docx)": "ورد (.docx)",
        "PDF (.pdf)": "پی‌دی‌اف (.pdf)",

        // Jobs
        "Waiting": "در انتظار",
        "Preparing audio…": "آماده‌سازی صدا…",
        "Transcribing…": "در حال تبدیل به متن…",
        "Saving…": "در حال ذخیره…",
        "Sending to Telegram…": "در حال ارسال به تلگرام…",
        "Paused": "متوقف",
        "Done": "انجام شد",
        "Failed: %@": "ناموفق: %@",
        "Cancelled": "لغو شد",
        "This file has no audio track.": "این فایل صدا ندارد.",
        "%d job(s) finished.": "%d کار انجام شد.",
        "%d job(s) finished, %d failed.": "%d کار انجام شد و %d کار ناموفق بود.",

        // Queue
        "The queue is empty": "صف خالی است",
        "Drop files anywhere in this window to add them.": "برای افزودن فایل، آن را در هر جای این پنجره رها کنید.",
        "Clear Finished": "پاک کردن کارهای تمام‌شده",
        "%d of %d done": "%d از %d انجام شد",
        "When everything is done": "وقتی همه‌ی کارها تمام شد",
        "Show a notification": "نمایش اعلان",
        "Play a sound": "پخش صدا",
        "Message me on Telegram": "پیام در تلگرام",
        "Quit Hush": "بستن هاش",
        "Put the Mac to sleep": "خواباندن مک",
        "Shut down the Mac": "خاموش کردن مک",
        "Notify me after each job": "بعد از هر کار اعلان نمایش داده شود",
        "Sound": "صدا",
        "Open": "باز کردن",
        "Show in Finder": "نمایش در فایندر",
        "Retry": "تلاش دوباره",
        "Move up": "بالاتر",
        "Move down": "پایین‌تر",
        "Remove": "حذف",
        "The Mac will shut down": "مک خاموش می‌شود",
        "The Mac will go to sleep": "مک به حالت خواب می‌رود",
        "All jobs are finished. This happens automatically in 30 seconds.": "همه‌ی کارها تمام شد. این کار تا ۳۰ ثانیه‌ی دیگر خودکار انجام می‌شود.",
        "Do it now": "همین حالا",

        // History and editor
        "Search transcripts": "جست‌وجو در متن‌ها",
        "Delete": "حذف",
        "No transcripts yet": "هنوز متنی ساخته نشده",
        "Finished transcripts appear here.": "متن‌های آماده اینجا نمایش داده می‌شوند.",
        "Choose a transcript": "یک متن انتخاب کنید",
        "lines": "خط",
        "Find and replace": "جست‌وجو و جایگزینی",
        "Copy all text": "کپی کل متن",
        "Copied": "کپی شد",
        "Export": "خروجی",
        "Text as a message": "متن به‌صورت پیام",
        "Text as a .txt file": "متن به‌صورت فایل .txt",
        "Subtitles as a .srt file": "زیرنویس به‌صورت فایل .srt",
        "Audio with the text as caption": "صدا با متن در کپشن",
        "Audio and the text separately": "صدا و متن به‌صورت جدا",
        "Audio only": "فقط صدا",
        "Save": "ذخیره",
        "Saved": "ذخیره شد",
        "Find": "جست‌وجو",
        "Replace with": "جایگزین با",
        "Replace All": "جایگزینی همه",
        "%d line(s) changed": "%d خط تغییر کرد",
        "Fix Persian text": "اصلاح متن فارسی",
        "Sent": "فرستاده شد",

        // Speak
        "Type or paste text and Hush reads it aloud. Save it as audio or send it to Telegram.": "متن را بنویسید یا بچسبانید تا هاش آن را بخواند. می‌توانید صدا را ذخیره کنید یا به تلگرام بفرستید.",
        "Text to read aloud…": "متنی که باید خوانده شود…",
        "Open text file…": "باز کردن فایل متنی…",
        "Voice": "صدا",
        "Automatic (by the text's language)": "خودکار (بر اساس زبان متن)",
        "macOS voices": "صداهای macOS",
        "Get Persian voices…": "دریافت صدای فارسی…",
        "Speed": "سرعت",
        "macOS has no Persian voice. Install Piper and a Persian voice in Settings → Voices.": "macOS صدای فارسی ندارد. Piper و یک صدای فارسی را از تنظیمات ← صداها نصب کنید.",
        "Play": "پخش",
        "Stop": "توقف",
        "Save Audio…": "ذخیره‌ی صدا…",
        "Send as voice": "ارسال به‌صورت ویس",
        "No voice is available.": "هیچ صدایی در دسترس نیست.",

        // Live
        "Speak into the microphone and the text appears as you talk. Everything stays on this Mac.": "در میکروفون صحبت کنید تا متن هم‌زمان نوشته شود. همه‌چیز روی همین مک می‌ماند.",
        "Loading the model…": "در حال بارگذاری مدل…",
        "Listening…": "در حال شنیدن…",
        "Click to start": "برای شروع کلیک کنید",
        "Language": "زبان",
        "Copy": "کپی",
        "Save as Text…": "ذخیره به‌صورت متن…",
        "Dictation": "گفتار",
        "Hush needs microphone access. Allow it in System Settings → Privacy & Security → Microphone.": "هاش به میکروفون دسترسی ندارد. آن را در تنظیمات سیستم ← حریم خصوصی و امنیت ← میکروفون فعال کنید.",
        "The speech server didn't start.": "سرور تبدیل گفتار اجرا نشد.",

        // Telegram page
        "Send results to Telegram, and let this Mac answer voice messages with text.": "نتیجه‌ها را به تلگرام بفرستید و ویس‌هایی را که برای ربات فرستاده می‌شود روی همین مک به متن تبدیل کنید.",
        "Bot": "ربات",
        "Save & Connect": "ذخیره و اتصال",
        "Answer voice messages (the Mac works as the bot's server while Hush is open)": "پاسخ به ویس‌ها (تا وقتی هاش باز است، مک سرور ربات است)",
        "Create a bot with @BotFather": "ساخت ربات با @BotFather",
        "Telegram lets bots download files up to 20 MB and upload up to 50 MB. Longer audio is split into parts automatically.": "تلگرام به ربات‌ها اجازه می‌دهد فایل تا ۲۰ مگابایت دریافت و تا ۵۰ مگابایت ارسال کنند. صدای طولانی‌تر خودکار چند بخش می‌شود.",
        "Connected as %@": "متصل با نام %@",
        "Connecting…": "در حال اتصال…",
        "Not running": "غیرفعال",
        "Pair your Telegram": "اتصال تلگرام شما",
        "Create a bot with @BotFather and paste its token above.": "با @BotFather یک ربات بسازید و توکن آن را در کادر بالا وارد کنید.",
        "Open your bot in Telegram and send /start.": "ربات را در تلگرام باز کنید و /start بفرستید.",
        "Open @%@": "باز کردن @%@",
        "Click “Allow” here on the Mac.": "روی همین مک «اجازه» را بزنید.",
        "Paired chats": "گفت‌وگوهای متصل",
        "Pairing is open": "اتصال باز است",
        "Close": "بستن",
        "Pair another chat": "اتصال گفت‌وگوی دیگر",
        "Opens pairing for 5 minutes. Then send /start from the other chat.": "اتصال را برای ۵ دقیقه باز می‌کند. سپس از گفت‌وگوی دیگر /start بفرستید.",
        "Default": "پیش‌فرض",
        "Make default": "پیش‌فرض شود",
        "Add by chat ID": "افزودن با شناسه‌ی گفت‌وگو",
        "Add": "افزودن",
        "Send test message": "ارسال پیام آزمایشی",
        "Sending results": "ارسال نتیجه‌ها",
        "Used when you choose “Also send the result to Telegram” on the Transcribe page.": "وقتی در صفحه‌ی «تبدیل به متن» ارسال به تلگرام را انتخاب کنید، از این تنظیمات استفاده می‌شود.",
        "Send the audio (extracted from videos)": "ارسال صدا (برای ویدیو، صدای جداشده)",
        "Send the text": "ارسال متن",
        "Captions are limited to 1024 characters. Longer text is sent as a separate message instead.": "کپشن حداکثر ۱۰۲۴ نویسه است. متن طولانی‌تر به‌صورت پیام جدا فرستاده می‌شود.",
        "Don't send the text": "متن فرستاده نشود",
        "As the audio's caption": "در کپشن صدا",
        "As a separate message": "به‌صورت پیام جدا",
        "As a .txt file": "به‌صورت فایل .txt",
        "As a .srt file": "به‌صورت فایل .srt",
        "Private chat": "گفت‌وگوی خصوصی",
        "Group": "گروه",
        "Channel": "کانال",
        "Unknown chat": "گفت‌وگوی ناشناس",
        "Chat %@": "گفت‌وگوی %@",
        "%@ wants to use Hush on this Mac.": "%@ می‌خواهد از هاش روی این مک استفاده کند.",
        "Only allow this if you sent /start yourself just now.": "فقط اگر خودتان همین الان /start فرستاده‌اید، اجازه دهید.",
        "Allow": "اجازه",
        "Deny": "رد",
        "Telegram pairing request": "درخواست اتصال تلگرام",
        "Add a bot token first.": "اول توکن ربات را وارد کنید.",
        "Pair a chat first.": "اول یک گفت‌وگو را متصل کنید.",
        "The bot token was rejected. Check it in the Telegram tab.": "توکن ربات پذیرفته نشد. آن را در بخش تلگرام بررسی کنید.",
        "Telegram didn't return the file.": "تلگرام فایل را برنگرداند.",

        // Bot messages
        "Send me a voice message, audio or video and I'll reply with the text. /help shows everything I can do.": "ویس، فایل صوتی یا ویدیو بفرستید تا متن آن را برایتان بفرستم. با /help همه‌ی دستورها را ببینید.",
        "🔒 This chat isn't paired yet. Send /start and approve it on your Mac.": "🔒 این گفت‌وگو هنوز متصل نشده. /start بفرستید و درخواست را روی مک تأیید کنید.",
        "🔒 Pair with me in a private chat first, then send /pair here.": "🔒 اول در گفت‌وگوی خصوصی متصل شوید، بعد اینجا /pair بفرستید.",
        "🔒 Pairing is closed. On your Mac open Hush → Telegram and click “Pair another chat”, then send /start again.": "🔒 اتصال بسته است. روی مک در هاش ← تلگرام، «اتصال گفت‌وگوی دیگر» را بزنید و دوباره /start بفرستید.",
        "👋 Hi! One last step: look at your Mac and click “Allow” in Hush.": "👋 سلام! یک قدم مانده: روی مک در پنجره‌ی هاش «اجازه» را بزنید.",
        "✅ Paired with %@!": "✅ به %@ متصل شد!",
        "✅ This chat is already paired with %@.": "✅ این گفت‌وگو از قبل به %@ متصل است.",
        "❌ Pairing was denied on the Mac.": "❌ درخواست اتصال روی مک رد شد.",
        "🗣 Spoken language: %@": "🗣 زبان گفتار: %@",
        "Usage: /lang auto, /lang fa or /lang en. Now: %@": "نحوه‌ی استفاده: /lang auto، /lang fa یا /lang en. تنظیم فعلی: %@",
        "📄 Replies will be sent as: %@": "📄 پاسخ‌ها با این قالب فرستاده می‌شوند: %@",
        "Usage: /format text, /format srt or /format both. Now: %@": "نحوه‌ی استفاده: /format text، /format srt یا /format both. تنظیم فعلی: %@",
        "💻 %@": "💻 %@",
        "📋 Jobs waiting: %d": "📋 کارهای در صف: %d",
        "⏳ Now: %@ (%d%%)": "⏳ در حال انجام: %@ (%d%%)",
        "🧠 Model: %@": "🧠 مدل: %@",
        "Usage: /tts followed by the text to read aloud.": "نحوه‌ی استفاده: /tts و بعد از آن متنی که باید خوانده شود.",
        "⚠️ Couldn't make the audio: %@": "⚠️ ساخت صدا انجام نشد: %@",
        "⚠️ Telegram lets bots download files up to 20 MB, and this one is bigger. Send a shorter clip or a compressed version.": "⚠️ تلگرام به ربات‌ها اجازه می‌دهد فقط فایل‌های تا ۲۰ مگابایت را دریافت کنند و این فایل بزرگ‌تر است. یک بخش کوتاه‌تر یا نسخه‌ی فشرده بفرستید.",
        "⏳ Got it. %d job(s) ahead of this one.": "⏳ دریافت شد. %d کار جلوتر از این فایل در صف است.",
        "⏳ Got it, transcribing…": "⏳ دریافت شد، در حال تبدیل به متن…",
        "⚠️ Couldn't get that file: %@": "⚠️ دریافت فایل انجام نشد: %@",
        "⚠️ Transcription failed: %@": "⚠️ تبدیل به متن انجام نشد: %@",
        "(No speech was found.)": "(گفتاری پیدا نشد.)",
        "👋 Test message from Hush on %@.": "👋 پیام آزمایشی از هاش روی %@.",
        "Hush turns voice messages, audio and video into text on its owner's Mac.\n\nTap Start, then approve the request on the Mac.": "هاش ویس، فایل صوتی و ویدیو را روی مک صاحب ربات به متن تبدیل می‌کند.\n\nروی Start بزنید و درخواست را روی مک تأیید کنید.",
        "Voice to text, powered by Hush on a Mac.": "تبدیل ویس به متن با هاش روی مک.",
        "What I can do": "کارهایی که انجام می‌دهم",
        "Spoken language: auto, fa or en": "زبان گفتار: auto، fa یا en",
        "Reply as text, srt or both": "پاسخ به‌صورت متن، srt یا هر دو",
        "Read text aloud": "خواندن متن با صدا",
        "What the Mac is working on": "کاری که مک در حال انجامش است",
        "Pair this chat with the Mac": "اتصال این گفت‌وگو به مک",
        """
        🎙 Send a voice message, audio file, video or video note and I'll reply with the text.

        /lang auto|fa|en — the spoken language
        /format text|srt|both — how the text comes back
        /tts <text> — read text aloud as a voice message
        /status — what the Mac is working on
        /help — this message
        """: """
        🎙 ویس، فایل صوتی، ویدیو یا ویدیوی دایره‌ای بفرستید تا متن آن را برایتان بفرستم.

        /lang auto|fa|en : زبان گفتار
        /format text|srt|both : قالب پاسخ
        /tts <متن> : خواندن متن و ارسال به‌صورت ویس
        /status : کاری که مک در حال انجامش است
        /help : همین راهنما
        """,

        // Settings
        "General": "عمومی",
        "Appearance": "ظاهر",
        "Models": "مدل‌ها",
        "Voices": "صداها",
        "Tools": "ابزارها",
        "Network": "شبکه",
        "About": "درباره",
        "Launch Hush at login": "اجرای هاش هنگام ورود به سیستم",
        "Show Hush in the menu bar": "نمایش هاش در نوار منو",
        "Keep the Mac awake while transcribing": "مک هنگام تبدیل به متن به خواب نرود",
        "Watch folders": "پوشه‌های زیر نظر",
        "Add Watch Folder…": "افزودن پوشه…",
        "New audio and video files in this folder are transcribed automatically.": "فایل‌های صوتی و ویدیویی تازه در این پوشه خودکار به متن تبدیل می‌شوند.",
        "Files dropped into these folders are added to the queue automatically.": "فایل‌هایی که در این پوشه‌ها گذاشته شوند، خودکار به صف اضافه می‌شوند.",
        "Finder": "فایندر",
        "Right-click audio or video files in Finder and choose Services → Transcribe with Hush. You can also drop files on the Hush icon in the Dock.": "در فایندر روی فایل صوتی یا ویدیویی راست‌کلیک کنید و Services ← Transcribe with Hush را بزنید. می‌توانید فایل را روی آیکون هاش در داک هم رها کنید.",
        "Background": "پس‌زمینه",
        "Liquid Glass": "شیشه‌ی مایع",
        "Translucent": "نیمه‌شفاف",
        "Solid": "یکدست",
        "Liquid Glass needs macOS 26 or later. Translucent is used instead.": "شیشه‌ی مایع به macOS 26 یا جدیدتر نیاز دارد. به‌جای آن حالت نیمه‌شفاف استفاده می‌شود.",
        "Color": "رنگ",
        "Opacity": "میزان پوشانندگی",
        "Blur": "محوشدگی",
        "Window": "پنجره",
        "Like Terminal: pick a color, then choose how much of the desktop shows through.": "مثل ترمینال: یک رنگ انتخاب کنید و تعیین کنید چه مقدار از پس‌زمینه‌ی دسکتاپ دیده شود.",
        "Theme": "پوسته",
        "System": "هماهنگ با سیستم",
        "Light": "روشن",
        "Dark": "تیره",
        "Speech models": "مدل‌های گفتار",
        "Refresh": "به‌روزرسانی فهرست",
        "Show every variant (English-only, other compressions)": "نمایش همه‌ی نسخه‌ها (فقط انگلیسی و فشرده‌سازی‌های دیگر)",
        "“large-v3-turbo-q5_0” is the best balance for Persian. Smaller models are faster but make more mistakes.": "«large-v3-turbo-q5_0» برای فارسی بهترین تعادل را دارد. مدل‌های کوچک‌تر سریع‌ترند ولی خطای بیشتری دارند.",
        "Voice activity detection": "تشخیص گفتار و سکوت",
        "Installed": "نصب‌شده",
        "Download": "دانلود",
        "Storage": "محل نگه‌داری",
        "Folder": "پوشه",
        "Choose where speech models are kept": "محل نگه‌داری مدل‌های گفتار را انتخاب کنید",
        "Download from": "دانلود از",
        "Recommended": "پیشنهادی",
        "Accuracy": "دقت",
        "English only": "فقط انگلیسی",
        "Use": "استفاده",
        "Couldn't load the model list (%@). Showing the built-in list.": "فهرست مدل‌ها دریافت نشد (%@). فهرست داخلی نمایش داده می‌شود.",
        "Download of %@ failed: %@": "دانلود %@ انجام نشد: %@",
        "The server answered with error %d.": "سرور خطای %d برگرداند.",
        "No speech model is downloaded yet. Open Settings → Models and download one.": "هنوز هیچ مدل گفتاری دانلود نشده. از تنظیمات ← مدل‌ها یک مدل دانلود کنید.",
        "Piper isn't installed. Install it in the Tools tab to use these natural voices.": "Piper نصب نیست. برای استفاده از این صداها، آن را از بخش ابزارها نصب کنید.",
        "Install Piper": "نصب Piper",
        "All": "همه",
        "Piper voices": "صداهای Piper",
        "Voices come from rhasspy/piper-voices on Hugging Face. Each voice has its own license; see its model card.": "صداها از مخزن rhasspy/piper-voices در Hugging Face دریافت می‌شوند. هر صدا مجوز جداگانه دارد که در کارت مدل آن آمده است.",
        "Couldn't load the voice list: %@": "فهرست صداها دریافت نشد: %@",
        "Command-line tools": "ابزارهای خط فرمان",
        "Hush uses these free tools. They are installed and updated with Homebrew, the standard package manager for macOS.": "هاش از این ابزارهای رایگان استفاده می‌کند. نصب و به‌روزرسانی آن‌ها با Homebrew، مدیر بسته‌ی رایج macOS، انجام می‌شود.",
        "Log": "گزارش",
        "optional": "اختیاری",
        "Install": "نصب",
        "Update": "به‌روزرسانی",
        "Check for Update": "بررسی به‌روزرسانی",
        "installed": "نصب‌شده",
        "Installs and updates the other tools.": "ابزارهای دیگر را نصب و به‌روز می‌کند.",
        "Turns speech into text, offline on this Mac.": "گفتار را بدون اینترنت روی همین مک به متن تبدیل می‌کند.",
        "Reads audio and video files and converts them.": "فایل‌های صوتی و ویدیویی را می‌خواند و تبدیل می‌کند.",
        "Natural text-to-speech voices, including Persian.": "صداهای طبیعی برای خواندن متن، از جمله فارسی.",
        "Homebrew is needed first. Install it above, then try again.": "اول Homebrew لازم است. آن را از بالا نصب کنید و دوباره تلاش کنید.",
        "Python 3 is needed for Piper. Install it with Homebrew (brew install python) and try again.": "Piper به Python 3 نیاز دارد. آن را با Homebrew نصب کنید (brew install python) و دوباره تلاش کنید.",
        "The Homebrew installer opened in Terminal. Follow its steps, then click Refresh.": "نصب‌کننده‌ی Homebrew در ترمینال باز شد. مراحل آن را انجام دهید و بعد «به‌روزرسانی فهرست» را بزنید.",
        "Failed with code %d": "با کد %d ناموفق بود",
        "Proxy": "پراکسی",
        "No proxy": "بدون پراکسی",
        "Host": "میزبان",
        "Port": "پورت",
        "Used for downloading models and voices, for Telegram and for update checks. Transcription itself never goes online.": "برای دانلود مدل‌ها و صداها، تلگرام و بررسی به‌روزرسانی استفاده می‌شود. خود تبدیل به متن هیچ‌وقت به اینترنت وصل نمی‌شود.",
        "Some tools Hush needs aren't installed: %@": "بعضی ابزارهای موردنیاز هاش نصب نیستند: %@",
        "Open Tools": "باز کردن ابزارها",
        "%@ isn't installed. Open Settings → Tools to install it.": "%@ نصب نیست. از تنظیمات ← ابزارها آن را نصب کنید.",
        "Couldn't read this file. It may be damaged or not a media file.": "این فایل خوانده نشد. ممکن است خراب باشد یا فایل صوتی و تصویری نباشد.",
        "Couldn't convert the audio: %@": "تبدیل صدا انجام نشد: %@",
        "whisper-cli failed: %@": "اجرای whisper-cli ناموفق بود: %@",
        "Couldn't create the Word file.": "فایل ورد ساخته نشد.",
        "Couldn't create the PDF.": "فایل پی‌دی‌اف ساخته نشد.",

        // About and updates
        "Version %@": "نسخه‌ی %@",
        "Free and open source. Everything to text, right on your Mac.": "رایگان و متن‌باز. تبدیل هر صدایی به متن، روی همین مک.",
        "Built with": "ساخته‌شده با",
        "Hush runs these tools as separate programs and does not include their code.": "هاش این ابزارها را به‌صورت برنامه‌ی جداگانه اجرا می‌کند و کد آن‌ها را در خود ندارد.",
        "· Released under the MIT License.": "· منتشرشده با مجوز MIT.",
        "Version %@ is available": "نسخه‌ی %@ آماده است",
        "Update & Relaunch": "به‌روزرسانی و اجرای دوباره",
        "Release Notes": "یادداشت انتشار",
        "Downloading the update…": "در حال دانلود به‌روزرسانی…",
        "You're up to date": "نسخه‌ی شما به‌روز است",
        "Check Again": "بررسی دوباره",
        "Try Again": "تلاش دوباره",
        "Check for Updates": "بررسی به‌روزرسانی",
        "Check for updates automatically": "بررسی خودکار به‌روزرسانی",
        "Couldn't reach GitHub": "اتصال به گیت‌هاب برقرار نشد",
        "Hush %@ is available. Open Settings → About to update.": "نسخه‌ی %@ هاش آماده است. برای به‌روزرسانی به تنظیمات ← درباره بروید.",
        "The update isn't signed by Hush's release key.": "این به‌روزرسانی با کلید انتشار هاش امضا نشده است.",
        "Couldn't unzip the update.": "فایل به‌روزرسانی باز نشد.",
        "The download doesn't look like Hush.": "فایل دانلودشده نسخه‌ی معتبری از هاش نیست.",
        "Couldn't write to %@. Drag the new app there yourself.": "امکان نوشتن در %@ نبود. برنامه‌ی جدید را خودتان به آنجا بکشید.",
        "Speech recognition engine (whisper-cli, whisper-server) by Georgi Gerganov and ggml-org": "موتور تشخیص گفتار (whisper-cli و whisper-server) از Georgi Gerganov و ggml-org",
        "The speech recognition models": "مدل‌های تشخیص گفتار",
        "Reading and converting audio and video": "خواندن و تبدیل صدا و ویدیو",
        "Natural text-to-speech voices, by the Open Home Foundation": "صداهای طبیعی برای خواندن متن، از Open Home Foundation",
        "Voice models, including Persian; each voice has its own license": "مدل‌های صدا از جمله فارسی؛ هر صدا مجوز جداگانه دارد",
        "Detecting speech and silence": "تشخیص گفتار و سکوت",
        "Installing and updating the tools": "نصب و به‌روزرسانی ابزارها",
        "Sending results and the voice-to-text bot": "ارسال نتیجه‌ها و ربات تبدیل ویس به متن",
        "Hosting the models and voices": "میزبانی مدل‌ها و صداها",

        // Onboarding and menu bar
        "Welcome to Hush": "به هاش خوش آمدید",
        "Three quick checks and you're ready.": "سه بررسی کوتاه، و همه‌چیز آماده است.",
        "whisper.cpp and FFmpeg are installed.": "whisper.cpp و FFmpeg نصب هستند.",
        "Install Homebrew": "نصب Homebrew",
        "Speech model": "مدل گفتار",
        "Using %@.": "مدل فعلی: %@",
        "Downloading large-v3-turbo-q5_0…": "در حال دانلود large-v3-turbo-q5_0…",
        "large-v3-turbo-q5_0 (574 MB) works well for Persian and English.": "مدل large-v3-turbo-q5_0 (۵۷۴ مگابایت) برای فارسی و انگلیسی مناسب است.",
        "Most of my recordings are in": "زبان بیشتر فایل‌های من",
        "Start using Hush": "شروع کار با هاش",
        "Bot online": "ربات فعال",
        "Bot off": "ربات خاموش",
        "Nothing in the queue.": "صف خالی است.",
        "%d waiting": "%d در صف",
        "Open Hush": "باز کردن هاش",
        "Live Dictation": "گفتار زنده"
    ]
}
